language: node_js
node_js:
  - '11'
services:
  - mongodb
install:
  - npm install -g codecov istanbul@1.0.0-alpha.2
script:
  - istanbul cover _mocha --reporter lcovonly -- -R spec
  - codecov
