language: node_js
node_js:
  - '11'
  - '10'
services:
  - mongodb
install:
  - npm install -g codecov
script:
  - test
sudo: false
after_success:
  - ./bin/codecov -e TRAVIS_NODE_VERSION -f coverage/*.json
