language: node_js
node_js:
  - '11'
services:
  - mongodb
install:
  - npm install -g codecov istanbul mocha
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
